language: node_js
node_js: "16"

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.2
      script: 
        - rm -f package-lock.json
        - npm run dist:mw
        - ls dist/
      before_cache: rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy Linux
      if: tag IS present
      os: linux
      dist: xenial
      script: 
        - rm -f package-lock.json
        - npm run dist:linux
        - ls dist/


deploy:
  provider: releases
  api_key:
    secure: "UyDNfcX7M43W+0c+Z1J+biJmDSy3ikP4LosQ98p4FP0hcrRghCQJIdednjmI9aE1rEmlPnJ8CIEeGLSz/BhVoDhCslycQVIvRF9LwWBAkjkguYQUIZBa9+r8Wu9MdODoNxY2ltgpxRZ/uvEECsCBnfI3Zsh7vS33iabSVknWQ9vz0CMmGHIBNXs2wH694RieurCGGwy7uVMM3JjLEcUaSbaRNKQKrj3Od5NrBv1qy4yxTgL1G790ggVpR8K3qQ6LYdKRlNZJ6re080e74EgRj5LTFmHEm8i9wZH5DOry+taQx3mXs+iS7s0iywSvRg2ngQZAs4nFmEy4PY2HdQNGQAB40XWGevsGX6CZKLOEYX7L+CmUguUn1n998JpbPe/QezdO8YnNBQSYyP6hlaGx2pa16eDFzYAP1O4PUuBk4ERa7A22LnKtWt2gaOb+wcCG5l/Njp3F6r+G/BGaZ6MZ1LI+FbEgLlx/9hLwnTtbFlAzlB8uMyApSl60v1Ge//XOG+QON87d42Ogm/aQvXDqyHcHUap+0dpeRw50s0nxFzkWszz3TSg/u/XSdYXkT9euevCxJhxLqWwXCBbjzjfpZM2Wdg/H3sxpV4p9XSer9mzSMXelVmiTnNcRiy4tXvnVprwSocDPoTrVzEYhdubENhmQ3rGD7dX0XJ3bqgPQIdw="
  file_glob: true
  file: "dist/YouTube-Music-Client*.{zip,exe,AppImage,dmg}"
  skip_cleanup: true
  on:
    tags: true
  draft: true
