language: node_js
node_js: '16'
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
jobs:
  include:
  - stage: Deploy Windows & Mac
    if: tag IS present
    os: osx
    osx_image: xcode10.2
    script:
    - rm -f package-lock.json
    - npm run dist:mw
    - ls dist/
    before_cache: rm -rf $HOME/.cache/electron-builder/wine
  - stage: Deploy Linux
    if: tag IS present
    os: linux
    dist: xenial
    script:
    - rm -f package-lock.json
    - npm run dist:linux
    - ls dist/
deploy:
  provider: releases
  api_key:
    secure: H++fKvIy2OiJcDryUqUc+KKVZrBYWU7/k44ifoGCtT26aGVXAaaUm1r3lrTUlC8PI/mITyfp/fD7CGUMa9ABJrRPFYXYRK8nOoQR50K0vzRDOnBw505eiufSSGavun82m2/recbdn6f0nZeAosvVHv7rQkLhA5E4mCQ4YPUW9Zidr0AY8xFaeUtJahGWfGqWKiX+5xLlHREtHaPTm5w8XYr+yFNkV2of30XvCDFJWSf9fF8OZxRsHO+Z4crXp1+5JCqPahX98WpkZ/ypROX/4MZaBA3mxYh8DPLBxAqpabaHciEfaw6fIKvYlq1UGQKZ32App/7CAOO2wRpOluHDb4JXHEhoYFHSEQz8g0BmsR+Te/2d+Eqmqokv4MXywhNVTARQFNQeJuAvS9jniZrxdHaHqBn5HwBOajn5lbO6o6m8fLVYEjjtjHjtFIkRiPmmlY7BXXucu3rAyM0zznHzbg6n4EfnuudMkQ+s3wnSqx3CDwKuZunuENDiVjjkPZgxbefMYOW9bnOZUv7KBd994anMpVxQVsfLGtY4/ilruF+IKnVCvEW9JAU4IFFf5TcowtYX8hP4+vgJts6gkQUCzG8fVZPHF8aaTJtHig3zHHPQK3lqN4AiENP5lfVSemIKNlXNlL4YE+sJ0piOddFkeWGgrouoXU5yeqUnWyo2nFs=
  file_glob: true
  file: dist/YouTube-Music-Client*.{zip,exe,AppImage,dmg}
  skip_cleanup: true
  on:
    tags: true
  draft: true
